### ISSUE TITLE
2023-11 ToDo

### ISSUE THREAD

**Issue by SuhyeonP** [SuhyeonP/SuhyeonP#4]
### 남은일들

- [ ] 트리쉐이킹 가능한 방향으로 패키지 만들기 - 롤업 알아보기
- [ ] microfrontend 조사
- [ ] Module Federation 조사
- [ ] Next.js 13 버전 학습
- [ ] Next.js server 학습 - api 이외에 다른것들
- [ ] grid row 조절되는거같은 2줄 혹은 n줄에서 리스트 줄세우는거 가능할지 체크
- [ ] next 템플릿 만들기
- [ ] date-preset 업뎃하기 - 레거시는 남겨두고 메모리 누수 최대한 적을것으로 확인 intl 서버사이드렌더링 체크
- [ ]  [click vs onClick](https://nangman14.tistory.com/27) 차이 뭔데? - [블로그 2](https://velog.io/@leitmotif/onClick-vs-addEventListener)

**Comment by SuhyeonP** [comment]
### 2023.11.04

- [ ] 실험실 레포 스토리북 추가 - 크로메틱 배포
- [ ] 실험실 css 정리해둔거 옮기기 (그리드기능)
- [ ] js 노션 내용들 옮기기 (실행가능할만한것들)
- [ ] headless ui 디자인시스템 만들기
- [ ] microfrontend 조사
- [ ] Module Federation 조사

**Comment by SuhyeonP** [comment]
> ### 2023.11.04
> * [v] 실험실 레포 구조 변경 (이벤트 하나 옮김...)
> * [ ]  실험실 css 정리해둔거 옮기기 (그리드기능)
> * [v]  js 노션 내용들 옮기기 (실행가능할만한 것들)
> * [ ]  headless ui 디자인시스템 만들기
> * [ ]  microfrontend 조사
> * [ ]  Module Federation 조사

**Comment by SuhyeonP** [comment]
> > ### 2023.11.05
> > 
> > * [v] 실험실 레포 구조 변경 (이벤트 하나 옮김...)
> > * [v] 실험실 css 정리해둔거 옮기기 (그리드기능)
> > * [v]  js 노션 내용들 옮기기 (실행가능할만한 것들)
> > * [v]   headless ui 디자인시스템 만들기 - gist 컴포넌트.
> > * [ ]   microfrontend 조사
> > * [v]   Module Federation 조사 - [link](https://www.notion.so/iam-suhyeon/b9d948b452004f20944b22f4f7ff074e?pvs=4)

**Comment by SuhyeonP** [comment]
11.05 갑지기 깃 액션에 빠져서 2시간이나 자동머지 마켓플레이스꺼 안 가져다 쓸려고.. 마이크로프론트엔드는 보지도 못했다...
